# Generated by Django 5.0.2 on 2024-02-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_entity',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
