# Generated by Django 5.0.2 on 2024-02-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_user_entity_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_entity',
            name='address',
        ),
        migrations.AddField(
            model_name='user_entity',
            name='address_line_1',
            field=models.CharField(default='BingBong', max_length=150, verbose_name='Address Line 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_entity',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=150, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='user_entity',
            name='country',
            field=models.CharField(default='BongBing', max_length=150, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_entity',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='user_entity',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AddField(
            model_name='user_entity',
            name='pin_code',
            field=models.CharField(default='Hehe', max_length=150, verbose_name='PIN Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_entity',
            name='state',
            field=models.CharField(default='S', max_length=150, verbose_name='City'),
            preserve_default=False,
        ),
    ]
