# Generated by Django 5.0.2 on 2024-02-28 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_user_entity_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='External_Participant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='external_participant', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('organization', models.CharField(max_length=100, verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'External Participant',
                'verbose_name_plural': 'External Participants',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='organizer', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Organizer',
                'verbose_name_plural': 'Organizers',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('roll_number', models.CharField(max_length=100, unique=True, verbose_name='Roll Number')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.AlterField(
            model_name='user_entity',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('external_participant', 'External Participant'), ('organizer', 'Organizer')], default='student', max_length=40, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='volunteer', serialize=False, to='webapp.student')),
                ('hours', models.IntegerField(verbose_name='Hours')),
            ],
            options={
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteers',
            },
        ),
    ]
